### ISSUE TITLE
TypeError: initial.siblings.map(...).map(...).concat(...).flat is not a function

### ISSUE THREAD

**Issue by Shackless** [leebenson/reactql#144]
With the latest release, I get the following error after trying to load the start page:

```
Error: TypeError: initial.siblings.map(...).map(...).concat(...).flat is not a function
    at Stats.scripts (C:\Source\reactql\src\lib\stats.ts:63:8)
    at eval (webpack-internal:///./src/entry/server.tsx:72:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

To reproduce the error, just clone the repo, run `npm i` and `npm start`. Then navigate to http://localhost:3000.

**Comment by ZimboQC** [comment]
I’ve got this error with nodejs 10.5. Upgrade to 11.8 to solve it

**Comment by Shackless** [comment]
Thanks, that fixed it!

**Comment by JoeApperson** [comment]
Since the stats module is already using lodash, a quick way to fix this problem for Node < 11 is to just change the script vars assignment to look like this:
```
    const scripts: string[] = lodash.flatten<string>(
      initial.siblings
        .map((sibling: any) =>
          this.raw.chunks.find((chunk: any) => chunk.id === sibling)
        )
        .map((sibling: any) => sibling.files)
        .concat(initial.files))
      .filter((file: string) => file.endsWith(".js"))
      .map((file: string) => `/${file}`);

```
