### ISSUE TITLE
ReactQL Starter Kit giving errors with 'npm start'

### ISSUE THREAD

**Issue by nrydevopswatch** [leebenson/reactql#182]
I followed the instructions in the readme:
```
wget -qO- https://github.com/leebenson/reactql/archive/4.5.1.tar.gz | tar xvz
cd reactql-4.5.1
npm i
npm start
```
My Linux bash shell gives me the following errors about 'caniuse-light' being out of date:
```
â¹ Development mode
â¹ Building development server...
â¹ ï½¢hotï½£: WebSocket Server Listening on 0.0.0.0:38280
â¹ ï½¢hotï½£: Applying DefinePlugin:__hotClientOptions__
â¹ ï½¢hotï½£: webpack: Compiling...
â¹ ï½¢hotï½£: Applying DefinePlugin:__hotClientOptions__
â¹ ï½¢hotï½£: webpack: Compiling...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
â¹ ï½¢hotï½£: webpack: Compiling Done
â Running on http://0.0.0.0:3000
â¹ ï½¢wdmï½£: Compiled successfully.
Error: TypeError: initial.siblings.map(...).map(...).concat(...).flat is not a function
    at Stats.scripts (/home/rbruscoe/dev/reactql-4.5.1/src/lib/stats.ts:63:8)
    at eval (webpack-internal:///./src/entry/server.tsx:102:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

In another terminal window I run:
`npm update` and then `npm update caniuse-lite browserslist` 

When I launch localhost:3000 in the browser, I'm getting the message: "There was an error. Please try again later."

Node version: v10.19.0
npm version: 6.13.7

I also tried to update all the NPM packages inside the package.json to the latest versions using an NPM update tool. This did not helped and caused a lot more errors. 

Expected behavior: Download the latest version of ReactQL, run 'npm i' and then 'npm start' and launch and run the ReactQL starter kit app.

**Comment by queer** [comment]
Your node version is out of date.

**Comment by aquadesk** [comment]
I get different error on node 14

```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/lib/hotServerMiddleware.ts:93:5 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

93     Array.isArray(filename)
       ~~~~~~~~~~~~~~~~~~~~~~~
94       ? filename.find(asset => /\.js$/.test(asset))
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
95       : filename
   ~~~~~~~~~~~~~~~~
```

**Comment by aquadesk** [comment]
okay let's use 12

**Comment by aquadesk** [comment]
yarn didn't work. npm worked
