### ISSUE TITLE
Disable importing module in ssr[involves 'document']

### ISSUE THREAD

**Issue by michaelspeed** [leebenson/reactql#98]
i am using office-fabric for an project, the browser setup is fine by the ssr crashes - 
output log - 
`Debugger listening on ws://127.0.0.1:9229/264782e7-3bda-4113-bf2e-0def007d2151
For help see https://nodejs.org/en/docs/inspector
/Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@microsoft/load-themed-styles/lib/index.js:277
    var head = document.getElementsByTagName('head')[0];
               ^

ReferenceError: document is not defined
    at registerStyles (/Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@microsoft/load-themed-styles/lib/index.js:277:16)
    at applyThemableStyles (/Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@microsoft/load-themed-styles/lib/index.js:140:13)
    at /Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@microsoft/load-themed-styles/lib/index.js:82:13
    at measure (/Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@microsoft/load-themed-styles/lib/index.js:32:5)
    at Object.loadStyles (/Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@microsoft/load-themed-styles/lib/index.js:69:5)
    at Object.<anonymous> (/Users/michaelspeed/Desktop/react/atmiyo-final/node_modules/@uifabric/utilities/lib/scroll.scss.js:5:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)`

is there any way to remove importing of office-fabric in the server side?

**Comment by brunocramos** [comment]
@michaelspeed I had a similar problem but with window's navigator + Adyen's client-side SDK. In my case, considering I didn't need the sdk from start, my workaround was to lazyload it in a ComponentWillMount.

**Comment by leebenson** [comment]
@brunocramos's solution is the best, at least until React come out with new lifecycle methods to handle async loading.

You can also use the global `SERVER` boolean to determine whether you're running on the server, and only load if so. i.e.:

```
if (SERVER) {
  // add `import()` logic to grab the lib...
}
```
